export enum SOCIAL_NETWORK_TYPES {
  SN_UNKNOWN = 0,
  SN_FACEBOOK = 1,
  SN_GOOGLE = 2,
  SN_TWITTER = 3,
  SN_INSTAGRAM = 4,
  SN_YAHOO = 5,
  SN_LINKEDIN = 6,
}

export enum NOTIFICATION_TYPES {
  NT_UNKNOWN = 0,
  NT_EMAIL = 1,
  NT_PUSH = 2,
  NT_WHATSAPP = 3,
  NT_TELEGRAM = 4,
  NT_MESSENGER = 5,
}

/* Lifetime predefined values in miliseconds */
export enum PROJECT_LIFETIME_TYPES {
  LT_INHERIT = 0,
  LT_INFINITE = -1,
  LT_1HOUR = 3600000,
  LT_24HOURS = 86400000,
  LT_ONE_WEEK = 604800000,
  LT_ONE_MONTH = 2629743000,
  LT_ONE_YEAR = 31556926000,
}

export enum PROJECT_EMAIL_CONFIRMATION {
  EC_CONFIRMATION_REQUIRED = 0,
  EC_CONFIRMATION_NOT_REQUIRED = 1,
  EC_CONFIRMATION_REQUIRED_BY_TIME = 2,
}

export enum PROJECT_RECOVER_TYPE {
  RT_DISABLED = 0,
  RT_LINK = 1,
  RT_CODE = 2,
  RT_BOTH = 3,
}
