export enum APPLICATION_TYPES {
  APP_UNKNOWN = 0,
  APP_SERVICE,
  APP_ANDROID,
  APP_IOS,
  APP_WEB_SERVER_SIDE,
  APP_WEB_CLIENT_SIDE,
  APP_MAX,
}


export enum APPLICATION_IP_RESTRICTION {
  APP_IR_ALLOWED = 0,
  APP_IR_BLOCKED = 1,
}
